<?php


namespace Braunstetter\AssetsPushBundle\Test\app\src;

use JetBrains\PhpStorm\Pure;
use Symfony\Bundle\FrameworkBundle\FrameworkBundle;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Bundle\TwigBundle\TwigBundle;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

class TestKernel extends Kernel
{

    use MicroKernelTrait;

    /**
     * @inheritDoc
     */
    #[Pure] public function registerBundles(): iterable
    {
        return [
            new FrameworkBundle(),
            new TwigBundle()
        ];
    }

    protected function configureContainer(ContainerConfigurator $container)
    {
        $container->extension('framework', [
            'secret' => "F00",
            'router' => ['utf8' => true]
        ]);

        $container->extension('twig', [
            'paths' => ['tests/app/src/Resources/views' => '__main__']
        ]);

        $container->import('Resources/config/services.test.yaml');
        $container->import('Resources/config/controller_test.yaml');
    }

    protected function configureRoutes(RoutingConfigurator $routes)
    {
        $routes->import(__DIR__ . '/Resources/config/routes.test.yaml');
    }

    public function getProjectDir()
    {
        return parent::getProjectDir(); // TODO: Change the autogenerated stub
    }


}